name: CI/CD pipeline

#Especifica os eventos que disparam o workflow
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    #Especifica que o job deve ser executado em uma máquina virtual com o sistema operacional Ubuntu na versão mais recente.
    runs-on: ubuntu-latest
    steps:
    - name: Checando o código
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        . venv/bin/activate
        python manage.py test
